# 15.04.2026

project_name: WristTraumaDetection
run_name: yolo26n_p2

model:
  model_name: "/home/piotrs/Uni/masters/NN/WristTraumaDetection/ultralytics/ultralytics/cfg/models/26/yolo26-p2.yaml"
  weights: "yolo26n.pt"
  # all_default
